apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-apple
  labels:
    jobgroup: jobexample
spec:
  template:
   metadata:
    name: jobexample
    labels:
     jobgroup: jobexample
   spec:
     containers:
     - name: c
       image: hub.docker.zwq.io:5000/busybox
       command: ["sh","-C","echo Processing item apple && sleep 5"]
     restartPolicy: Never
