apiVersion: v1
kind: ReplicationController
metadata: 
 name: myweb
spec:
 replicas: 2
 selector:
  app: myweb
 template:
  metadata:
    labels:
       app: myweb
  spec:
    containers:
    - name: myweb
      image: hub.docker.zwq.io:5000/tomcat-app:v1
      ports:
      - containerPort: 8080
      env:
      - name: MYSQL_SERVICE_HOST
        value: '172.17.0.3'
      - name: MYSQL_SERVICE_PORT
        value: '3306'
