apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myweb
spec:
 replicas: 1
 selector:
  matchLabels:
    app: myweb
 template:
  metadata:
    labels:
       app: myweb
  spec:
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: zone
             operator: In
             values:
             - test
     podAntiAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
       - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values: 
            - nginx
         topologyKey: kubernetes.io/hostname
#     podAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#          matchExpressions:
#          - key: security
#            operator: In
#            values: 
#            - S1
#         topologyKey: failure-domain.beta.kubernetes.io/zone
   containers:
    - name: myweb
      image: hub.docker.zwq.io:5000/tomcat-app:v1 
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
      env:
      - name: MYSQL_SERVICE_HOST
#        value: '10.111.208.11'
        value: 'mysql'
      - name: MYSQL_SERVICE_PORT
        value: '3306'
