apiVersion: v1
kind: ReplicationController
metadata:
 name: frontend
 labels:
  name: frontend
spec:
 replicas: 1
 selector:
   name: frontend
 template:
  metadata:
   labels:
    name: frontend
  spec:
   containers:
   - name: php-redis
     image: hub.docker.zwq.io:5000/guestbook-php-frontend
     env:
     - name: GET_HOSTS_FROM
       value: env
     ports:
     - containerPort: 80
       hostPort: 80
