apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql1
spec:
  replicas: 1
  selector:
    app: mysql1
  template:
    metadata:
      labels:
         app: mysql1
    spec:
      containers:
      - name: mysql
        image: hub.docker.zwq.io:5000/mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
