apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
 containers:
 - name: cm-test
   image: docker.io/busybox:latest 
   imagePullPolicy: Always
   command: [ "/bin/sh","-c","env | grep App" ]
   env:
   - name: APPLOGLEVEL
     valueFrom:
       configMapKeyRef:
         name: cm-appvars
         key: apploglevel
   - name: APPDATADIR
     valueFrom:
       configMapKeyRef:
         name: cm-appvars
         key: appdatadir
 restartPolicy: Never
